# Generated by Django 3.1.7 on 2021-04-14 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='encuestavacunacion',
            name='fechav',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='encuestavacunacion',
            name='sexo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='encuesta.genero'),
        ),
    ]
