# Generated by Django 3.1.7 on 2021-04-14 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0002_auto_20210413_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacunado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vacuna', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='encuestavacunacion',
            name='vacunado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='encuesta.vacunado'),
        ),
    ]
