# Generated by Django 3.1.7 on 2021-04-16 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0003_auto_20210413_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='encuestavacunacion',
            old_name='fechav',
            new_name='fecha',
        ),
        migrations.RenameField(
            model_name='encuestavacunacion',
            old_name='sexo',
            new_name='genero',
        ),
    ]
